; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_nasu:
	db 3
	dw @instruments
	dw @samples-4
; 00 : Title Screen
	dw @song0ch0
	dw @song0ch1
	dw @song0ch2
	dw @song0ch3
	dw @song0ch4
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0
; 01 : Playing
	dw @song1ch0
	dw @song1ch1
	dw @song1ch2
	dw @song1ch3
	dw @song1ch4
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0
; 02 : Game Over
	dw @song2ch0
	dw @song2ch1
	dw @song2ch2
	dw @song2ch3
	dw @song2ch4
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env4,@env1,@env3,@env0 ; 00 : Instrument 1

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c0,$7f,$00,$01
@env2:
	db $7f,$00,$00
@env3:
	db $c2,$7f,$00,$00
@env4:
	db $00,$cb,$7f,$00,$02

@samples:

@tempo_env_1_mid:
	db $03,$05,$80

@song0ch0:
@song0ch0loop:
	db $47, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $00, $a5, $80
@song0ref8:
	db $29, $a5, $27, $a5, $29, $a5, $2a, $b9, $29, $b9, $27, $a5, $48, $25, $a5, $24, $a5, $25, $a5, $27, $a5, $25, $cd, $24
	db $a5, $25, $a5, $48, $00, $a5
	db $41, $15
	dw @song0ref8
	db $f5, $00, $a5, $42
	dw @song0ch0loop
@song0ch1:
@song0ch1loop:
	db $80, $19, $ff, $9d, $1e, $ff, $9d, $20, $ff, $9d, $1e, $ff, $9d, $19, $ff, $9d, $1e, $ff, $9d, $20, $cd, $1b, $cd, $19
	db $f5, $00, $a5, $42
	dw @song0ch1loop
@song0ch2:
@song0ch2loop:
@song0ref79:
	db $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $ff, $ff, $bf, $42
	dw @song0ch2loop
@song0ch3:
@song0ch3loop:
	db $41, $0c
	dw @song0ref79
	db $42
	dw @song0ch3loop
@song0ch4:
@song0ch4loop:
	db $41, $0c
	dw @song0ref79
	db $42
	dw @song0ch4loop
@song1ch0:
@song1ch0loop:
	db $47, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $80, $0d
@song1ref7:
	db $9d, $00, $9d, $1d, $9d, $20, $9d, $00, $fd, $48, $11
	db $41, $09
	dw @song1ref7
	db $42
	dw @song1ch0loop
@song1ch1:
@song1ch1loop:
	db $ff, $ff, $ff, $ff, $42
	dw @song1ch1loop
@song1ch2:
@song1ch2loop:
	db $ff, $ff, $ff, $ff, $42
	dw @song1ch2loop
@song1ch3:
@song1ch3loop:
	db $ff, $ff, $ff, $ff, $42
	dw @song1ch3loop
@song1ch4:
@song1ch4loop:
	db $ff, $ff, $ff, $ff, $42
	dw @song1ch4loop
@song2ch0:
	db $80, $19, $d5, $1b, $a9, $1d, $a9, $1e, $d5, $1d, $a9, $1e, $a9, $48, $22, $a9, $20, $a9, $22, $a9, $24, $a9, $25, $ff
	db $ad, $44, $00
@song2ch1:
	db $80, $0d, $ff, $ad, $0f, $ff, $ad, $12, $d5, $14, $d5, $0d, $ff, $ad, $44, $00
@song2ch2:
	db $ff, $ff, $df, $ff, $ff, $df, $44, $00
@song2ch3:
	db $ff, $ff, $df, $ff, $ff, $df, $44, $00
@song2ch4:
	db $ff, $ff, $df, $ff, $ff, $df, $44, $00
